---
title: "ingresantes 2026"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(flextable)

```

Importantes antes de importar la base de la encuesta se debe  ingluir columna con estudiantes (numerada de 1 hasta el último) y codificar las variables  ya está en Respesta26 3.xlsx

```{r}
rm(list = ls())
```


```{r}
library(readxl)
datos <- read_excel("datos/Respuestas.xlsx")
View(datos)
```

Variables

```{r}
names(datos)
```

```{r}
str(datos)

```

```{r}
datos %>%
  filter(DNI %in% DNI[duplicated(DNI)])
```

```{r}
datos_dup <- datos %>%
  filter(DNI %in% DNI[duplicated(DNI)]) %>%
  arrange(DNI)
```

```{r}
#alumnos duplicados 
datos_dup %>% arrange(DNI)
```

```{r}
#elimino los alumnos duplicados  (elimino la primer respuesta)
datos1 <- datos %>%
  filter(!estudiante %in% c(228, 47, 9,122,20,109,24))
```

```{r}
#datos1  tiene los registros NO duplicados 
nrow(datos)
nrow(datos1)
```

## Cargo datos por Carrera dados por Sección alumnos 

```{r}
A_LANA<- read_excel("datos/3- ASPIRANTES LANA 2026_mio.xlsx", 
    sheet = "Hoja1")
View(A_LANA)
```

```{r}
A_IA<- read_excel("datos/ASPIRANTES IA 2026_ mio.xlsx", 
    sheet = "Hoja1")
```



```{r}
sexo<-table(datos1$genero)
sexo_df <- as.data.frame(sexo)
colnames(sexo_df) <- c("Genero", "Frecuencia")
# Agregar porcentaje
sexo_df$Porcentaje <- round(100 * sexo_df$Frecuencia / sum(sexo_df$Frecuencia), 1)
sexo_df
```
```{r}
tabla_sexo<-flextable(sexo_df)

tabla_sexo <- set_caption(tabla_sexo, "Distribucion de estudiantes segun genero")
tabla_sexo <- bold(tabla_sexo, part = "header")

tabla_sexo


```
La muestra está foramda por  respuestas a las encuestas solictadas 

########### 

```{r}
# trasformo a factor aquellos atributos que son caracteres
datos1 <- datos1 %>%
  mutate(across(where(is.character), as.factor))
```

```{r}
#RECODIFICO LAS CARRERAS 

datos1 <- datos1 %>%
  mutate(carrera = case_when(
    carrera == "TUAA - Licenciatura en Administración de Negocios Agropecuarios" ~ "TUAA-LANA",
    
    carrera == "TUAA - Licenciatura en Administración de Negocios Agropecuarios, TGyTA" ~ "TUAA-LANA, TGyTA",
    
    carrera == "Ingeniería Agronómica, TUAA - Licenciatura en Administración de Negocios Agropecuarios" ~ 
      "IA, TUAA-LANA",

    carrera == "Ingeniería Agronómica" ~ 
      "IA",
    TRUE ~ carrera
  ))
```

```{r}
#funciones para acelerar porcentajes
tabla_prop <- function(x){
  round(prop.table(table(x)) * 100,1)
}

```

```{r}
unique(datos1$carrera)
```

```{r}

table(datos1$carrera)
tabla_carrerra<-table(datos1$carrera)
```

```{r}
IA_TUAA_LANA<- subset(datos1, grepl("IA, TUAA-LANA", carrera), select = c(nombre, DNI))
IA_TUAA_LANA
```
```{r}
# Busco coincidencias 
merge(IA_TUAA_LANA, A_IA, by = "DNI")
```

```{r}
# Busco coincidencias 
merge(IA_TUAA_LANA, A_IA, by = "DNI")
```

```{r}

subset(datos1, grepl("TUAA-LANA, TGyTA", carrera), select = c(nombre, DNI))

```


```{r}
vars_cat <- c("carrera", "genero", "estado_civil", 
               "trabaja", "provincia",
              "pueblos_originarios", 
              "padres_estudios_superiores",
              "adeuda_materias", "OV",
              "hermanos_estud_sup")

lapply(datos1[vars_cat], tabla_prop)
```

```{r}
library(dplyr)
library(stringr)

datos1 <- datos1 %>%
  mutate(personas_cargo = str_to_lower(personas_cargo),
         personas_cargo_cod = case_when(
           
           # 👉 SI (personas a cargo)
           str_detect(personas_cargo, "si|hijo|hijos|hija|hijas|niño|niños|niña|niñas|padre|padres|madre|madres|1 nene y por nacer una bebé|hermana|1|2") ~ "si",
           
           # 👉 NO
           str_detect(personas_cargo, "^no$|^no\\s|\\sno$|nada|0|solo|no, no tengo") ~ "no",
           
           # 👉 NR (vacíos o NA)
           is.na(personas_cargo) | personas_cargo == "" ~ "NR",
           
           # 👉 lo que no sabés, lo deja como está
           TRUE ~ personas_cargo
         ))
```

```{r}
table(datos1$provincia)
```

```{r}
library(dplyr)
library(stringr)
library(stringi)

datos1<- datos1 %>%
  mutate(
    # opcional: solo saco acentos (muy recomendable)
    PROVINCIA_clean = stri_trans_general(provincia, "Latin-ASCII"),
    
    PROVINCIA_cod = case_when(
      
      # 👉 Buenos Aires (incluye CABA)
      str_detect(PROVINCIA_clean, regex("buenos aires|ciudad autonoma", ignore_case = TRUE)) ~ "Buenos Aires",
      
      # 👉 La Pampa (aunque venga combinada)
      str_detect(PROVINCIA_clean, regex("la pampa", ignore_case = TRUE)) ~ "La Pampa",
      
      # 👉 resto
      TRUE ~ "Otras"
    )
  )

datos1$PROVINCIA_clean<-NULL
```

```{r}

table (datos1$genero)
```

```{r}
writexl::write_xlsx(datos1,"datos1.xlsx")
```
